files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - ./*.rb
    - views/*.rb
    - game/*.rb
    - file/*.rb
  # define files excluded from the analysis (defaults to [])
  excluded:
    - spec/**/*.rb
