# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Browser test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.3', '2.5', '2.6', '2.7', '3.0']
#    services:
#      selenium:
#        image: selenium/standalone-chrome:3.141.59-vanadium
#        ports:
#          - 4444:4444
#        volumes:
#          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup Firefox and geckodriver'
#     runs:
#       using: "composite"
#       steps:
      run: |
        GECKODRIVER_URL=`curl -Ls -o /dev/null -w %{url_effective} https://github.com/mozilla/geckodriver/releases/latest`
        GECKODRIVER_VERSION=`echo $GECKODRIVER_URL | sed 's#.*/##'`
        export GECKODRIVER_DOWNLOAD="https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        curl -L -o geckodriver.tar.gz $GECKODRIVER_DOWNLOAD
        gunzip -c geckodriver.tar.gz | tar xopf -
        chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
        geckodriver --version
#      shell: bash
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup gems
      run: |
        gem install webrick -v1.6.0
        gem install mailcatcher
        gem install selenium-webdriver -v3.141.5926  # -v3.142.7 # for ruby 2.1, 2.2
    - name: Install dependencies
      run: bundle install
    - name: launch xvfb
      run: Xvfb :99 &
    - name: launch mail server
      run: mailcatcher
    - name: launch web server
      run: |
        ruby ./travisci/webserver.rb &
        sleep 3 # give some software a moment to start
    - name: Run tests
      run: |
        chmod ugo+x ./travisci/runontravis.sh
        ./travisci/runontravis.sh
