# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Chrome test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.3', '2.5', '2.6', '2.7']  # , '3.0']
        kifu: ['-N0', '-N1', '-N2', '-N3', '-N4', '-N5', '-N6']
#    services:
#      selenium:
#        image: selenium/standalone-chrome:3.141.59-vanadium
#        ports:
#          - 4444:4444
#        volumes:
#          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup Google Chrome'
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -qqy
        sudo apt-get -qqy install google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version)
        CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
        CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
        sudo rm /etc/apt/sources.list.d/google-chrome.list
        export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
        curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
        export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
        curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
        chromedriver -version
#      shell: bash
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: ruby is here
      run: |
        which ruby
        /usr/bin/env ruby --version
    - name: Setup gems
      run: |
        gem install webrick -v1.7.0
        gem install mailcatcher
        gem install rubyzip -v1.3.0 # for selenium-webdriver -v3.142.7
        gem install selenium-webdriver -v3.142.7
    - name: launch xvfb
      run: Xvfb :99 &
    - name: launch mail server
      run: mailcatcher
    - name: launch web server
      run: |
        ruby ./travisci/webserver.rb &
        sleep 3 # give some software a moment to start
    - name: Run tests
      run: |
        chmod ugo+x ./travisci/runontravis.sh
        ./travisci/runontravis.sh ${{ matrix.kifu }}
      env:
        DISPLAY: :99
